- a
- an
- the
- and
- in
- at
- 'on'
- of
- for
- with
- about
- against
- between
- into
- through
- during
- before
- after
- above
- below
- to
- from
- up
- down
- out
- 'off'
- over
- under
- again
- further
- then
- once
- here
- there
- when
- where
- why
- how
- all
- any
- both
- each
- few
- more
- most
- other
- some
- such
- 'no'
- nor
- not
- only
- own
- same
- so
- than
- too
- very
- s
- t
- can
- will
- just
- don
- should
- now
