version: '3.9'

networks:
  net:
    driver: bridge

services:
  web:
    build:
      context: ../
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
    environment:
      FLASK_ENV: development
